### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by JimmyRoasts** [KatjaGlassConsulting/ApprovalBundle#16]
Hi, I've been getting the following error when trying to install the latest approvals module. I'm using Kimai 2.0.24

```
In PluginMetadata.php line 59:

  Bundle "ApprovalBundle" defines an invalid Kimai minimum version in extra.kimai.require. Please provide an integer as in Constants::VERSION_ID.
```

I'm having a little trouble finding PluginMetadata.php, I was wondering if you could point me in the right direction? Thanks

**Comment by KatjaGlassConsulting** [comment]
Hi, it is in the root directory. The file is named "composer.json" under require you see "1.17" - but I see you are using the newest Kimai version which is 2 (the first offical release is just out since 2 weeks), the approvalBundle did not include updates required for the complete new 2er version, so it will very likely not run.

**Comment by JimmyRoasts** [comment]
No worries, thanks for letting me know
