### ISSUE TITLE
Support Sunday as Start of Week

### ISSUE THREAD

**Issue by tjpbwt** [KatjaGlassConsulting/ApprovalBundle#18]
Would it be possible to look into supporting Sunday as the work week start date? This would be helpful when all users are in the same time zone. 

I'd be happy to try taking a look at this in my free time if I had a little context to any known technical issues that would break functionality if the work week was set to start on Sunday. 

Thank you.

**Comment by hsachan22** [comment]
Have you found any solution regarding this?

**Comment by KatjaGlassConsulting** [comment]
Hi, it would be possible to create a new option to have either only mondays or only sundays. 

That could be implemented easily by adding this option and change all checks to that setting instead of Monday. Switching is tricky, there must be no approvals so far or all approved weeks will change the day.

I am in summer break and need to follow up other things. I would expect to implement this in autumn.

**Comment by KatjaGlassConsulting** [comment]
This topic is more tricky and for this I put this request unluckily "on-hold". There is the branch `sundayWeekStart`, but it is not working.

**Comment by KatjaGlassConsulting** [comment]
Due to complexity close this as not planned.

**Comment by vitormattos** [comment]
Maybe we can maintain as open and assign a label like 'backlog' or 'not planned' or anything else like this.

**Comment by MitchellArtz** [comment]
For my work, I've created an experimental fork with additional enhancements (which I may try to bring back to the original) that uses a Sunday start day. Very experimental, but may help someone. 

Please don't use in production, and keep in mind it likely has quite a few bugs as it's a prototype and generated largely using AI

MitchellArtz/ApprovalBundleSunday
