### ISSUE TITLE
Auto Submit for Previous Weeks?

### ISSUE THREAD

**Issue by corrigenda-admin** [KatjaGlassConsulting/ApprovalBundle#38]
Hi,

This is more a feature request, currently when someone tries to Submit a week but missed a week it comes up with the warning:

"Please add previous weeks to approve".

When people have a couple of weeks off on holiday, they have to go back and do previous weeks. Is it possible to get it to auto submit any previous weeks by default? Like a round up? Wasnt sure if thats possible?

Thanks.

Mike

**Comment by KatjaGlassConsulting** [comment]
Hi Mike,

I think such a functionality might quite often be ticked also accidently. I would recommend to always check-in every week for approval after review, otherwise a week might be accidently submitted without even checking. Personally I think the risk is higher than the benefit. For this I close this issue, but I will include this into the "Discussions" sections, as if more find such a thing useful, it might become implemented.
