### ISSUE TITLE
How can I use display name (Alias) instead of login username?

### ISSUE THREAD

**Issue by hifred** [KatjaGlassConsulting/ApprovalBundle#6]
Need help on customizing the display of names and date ranges, can it be the same of other parts of kimai?

Appreciate your work on this awesome plugin!

**Comment by KatjaGlassConsulting** [comment]
Hi, using the displayName (Alias when available, otherwise username) is a nice feature. This will be available in the next update (expected within 2 weeks). You can use the "dev" version for now.

For the date-ranges - it is a standard form which Kimai uses - you see the same under "Administration" -> "Reporting". When you are familar with Kimai programming, feel free to update the file: WeeklyUserListForm.php.

![image](https://user-images.githubusercontent.com/55694577/191003033-1f1bd8bf-d286-4978-a4d2-a9105716248d.png)

**Comment by hifred** [comment]
thank you!

btw, the date ranges format is fine, it's just not localized, that's what I mean😃

I duplicated the file 'messages.en.xliff' to make my own localization, but the month names like 'September' are not covered.

**Comment by KatjaGlassConsulting** [comment]
The "date-ranges" form is one from Kimai - it might be reported there to localize this - no changes in the approvalBundle are possible for this. The alias will come soon also for "main", so I close this issue.
